/* eslint-disable no-undef */
/**
 * Revvin service worker. Plain JavaScript, copied to /sw.js at build time with
 * __VERSION__ and __PRECACHE__ filled in by plugins/pwa.ts.
 *
 * Written by hand rather than generated by vite-plugin-pwa because the SEO
 * prerender plugin rewrites and adds HTML documents in dist AFTER the bundle
 * closes: a generated precache manifest would either miss those documents or
 * pin stale revisions of them. The rule that follows from the same constraint:
 * this worker NEVER caches HTML. Crawlers and first visits always get the fresh
 * prerendered document from the network; the only HTML it can serve is the
 * offline page, and only when the network actually failed.
 */

const VERSION = "__VERSION__";
const PRECACHE = "revvin-precache-" + VERSION;
const ASSETS = "revvin-assets-v1";
const IMAGES = "revvin-images-v1";
const KEEP = [PRECACHE, ASSETS, IMAGES];

const OFFLINE_URL = "/offline.html";
const PRECACHE_URLS = __PRECACHE__;

const NAV_TIMEOUT_MS = 4000;
const IMAGE_MAX_ENTRIES = 60;
const IMAGE_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000;

/** Anything that must never be intercepted, cached or replayed. */
function isExcluded(request, url) {
  if (request.method !== "GET") return true;
  if (url.origin !== self.location.origin) {
    // Third party: Supabase, Stripe, fonts and analytics all go straight to the
    // network. Nothing cross origin is cached.
    return true;
  }
  if (url.pathname === "/auth" || url.pathname.startsWith("/auth/")) return true;
  if (url.pathname.startsWith("/login") || url.pathname.startsWith("/signup")) return true;
  if (url.pathname.startsWith("/reset-password")) return true;
  if (
    url.pathname.startsWith("/rest/v1") ||
    url.pathname.startsWith("/auth/v1") ||
    url.pathname.startsWith("/storage/v1") ||
    url.pathname.startsWith("/functions/v1")
  ) {
    return true;
  }
  if (url.search.includes("sw=off")) return true;
  return false;
}

const isAsset = (url) =>
  url.pathname.startsWith("/assets/") ||
  /\.(js|mjs|css|woff2?|ttf|otf)$/i.test(url.pathname);

const isImage = (url) => /\.(png|jpe?g|webp|avif|gif|svg|ico)$/i.test(url.pathname);

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE);
      await Promise.allSettled(PRECACHE_URLS.map((u) => cache.add(new Request(u, { cache: "reload" }))));
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.allSettled(
        names
          .filter((n) => n.startsWith("revvin-") && KEEP.indexOf(n) === -1)
          .map((n) => caches.delete(n)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

/** Network first with a timeout. Falls back to the offline page, never to HTML from cache. */
async function handleNavigation(request) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), NAV_TIMEOUT_MS);
  try {
    const response = await fetch(request, { signal: controller.signal });
    clearTimeout(timer);
    return response;
  } catch (err) {
    clearTimeout(timer);
    const cache = await caches.open(PRECACHE);
    const offline = await cache.match(OFFLINE_URL);
    if (offline) return offline;
    return new Response("You are offline.", {
      status: 503,
      headers: { "Content-Type": "text/plain" },
    });
  }
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(ASSETS);
  const cached = await cache.match(request);
  const network = fetch(request)
    .then((response) => {
      if (response && response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => null);
  if (cached) return cached;
  const fresh = await network;
  if (fresh) return fresh;
  throw new Error("asset unavailable offline");
}

async function trimImages(cache) {
  const keys = await cache.keys();
  const now = Date.now();
  for (const key of keys) {
    const hit = await cache.match(key);
    const stored = hit && hit.headers.get("date");
    if (stored && now - new Date(stored).getTime() > IMAGE_MAX_AGE_MS) await cache.delete(key);
  }
  const left = await cache.keys();
  if (left.length > IMAGE_MAX_ENTRIES) {
    await Promise.allSettled(left.slice(0, left.length - IMAGE_MAX_ENTRIES).map((k) => cache.delete(k)));
  }
}

async function cacheFirstImage(request) {
  const cache = await caches.open(IMAGES);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && response.ok) {
    await cache.put(request, response.clone());
    trimImages(cache);
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (isExcluded(request, url)) return;

  if (request.mode === "navigate" || (request.headers.get("accept") || "").includes("text/html")) {
    event.respondWith(handleNavigation(request));
    return;
  }
  if (isAsset(url)) {
    event.respondWith(staleWhileRevalidate(request));
    return;
  }
  if (isImage(url)) {
    event.respondWith(cacheFirstImage(request));
  }
});

/* Web push ---------------------------------------------------------------- */

self.addEventListener("push", (event) => {
  let payload = {};
  try {
    payload = event.data ? event.data.json() : {};
  } catch (err) {
    payload = { title: "Revvin", body: event.data ? event.data.text() : "" };
  }
  const title = payload.title || "Revvin";
  event.waitUntil(
    self.registration.showNotification(title, {
      body: payload.body || "",
      icon: "/icons/icon-192.png",
      badge: "/icons/badge-96.png",
      tag: payload.tag || "revvin",
      renotify: true,
      data: { url: payload.url || "/dashboard" },
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || "/dashboard";
  event.waitUntil(
    (async () => {
      const clientsList = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of clientsList) {
        if (new URL(client.url).origin === self.location.origin) {
          await client.focus();
          if ("navigate" in client) await client.navigate(target);
          return;
        }
      }
      await self.clients.openWindow(target);
    })(),
  );
});

self.addEventListener("pushsubscriptionchange", (event) => {
  event.waitUntil(
    (async () => {
      const oldEndpoint = event.oldSubscription ? event.oldSubscription.endpoint : null;
      let fresh = event.newSubscription || null;
      if (!fresh) {
        try {
          fresh = await self.registration.pushManager.subscribe({
            userVisibleOnly: true,
            applicationServerKey: "__VAPID_PUBLIC_KEY__",
          });
        } catch (err) {
          return;
        }
      }
      try {
        await fetch("__RESUBSCRIBE_URL__", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ old_endpoint: oldEndpoint, subscription: fresh.toJSON() }),
        });
      } catch (err) {
        /* the next opt-in from the app re-registers the subscription */
      }
    })(),
  );
});
