import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import SEOHead from "@/components/SEOHead";
import { useMockListing } from "@/hooks/useMockListings";
import ContactBusinessDialog from "@/components/marketplace/ContactBusinessDialog";
import SimpleQRCode from "@/components/marketplace/SimpleQRCode";
import { Sparkles, ArrowLeft, Share2, QrCode, UserPlus, CheckCircle2 } from "lucide-react";

function hashHue(s: string) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) % 360;
  return h;
}

export default function ReferralPreview() {
  const { slug } = useParams();
  const { data: listing, isLoading } = useMockListing(slug);

  if (isLoading) return <div className="container py-24 text-sm text-muted-foreground">Loading…</div>;
  if (!listing) {
    return (
      <div className="container py-24">
        <p className="text-sm text-muted-foreground">Referral page not found.</p>
        <Button asChild className="mt-4"><Link to="/browse">Back to browse</Link></Button>
      </div>
    );
  }

  const hue = hashHue(listing.name);
  const accent = `hsl(${hue} 60% 38%)`;
  const wash = `hsl(${hue} 60% 96%)`;
  const initials = listing.name.split(" ").map((n) => n[0]).slice(0, 2).join("");
  const url = typeof window !== "undefined" ? `${window.location.origin}/refer/${listing.slug}` : `https://revvin.co/refer/${listing.slug}`;

  return (
    <>
      <SEOHead
        title={`Refer ${listing.name} — earn $${listing.referral_fee}`}
        description={`Refer a friend or family member to ${listing.name} and earn $${listing.referral_fee} ${listing.referral_fee_unit}.`}
        path={`/refer/${listing.slug}`}
      />

      {/* Sample banner */}
      <div className="border-b border-border bg-amber-50 text-amber-900">
        <div className="container flex flex-wrap items-center justify-between gap-3 py-2 text-xs">
          <p>
            <span className="font-semibold">Sample referral page.</span> This is what a {listing.name} customer sees — generated by Revvin and branded for the business.
          </p>
          <Link to={`/business/${listing.slug}`} className="font-semibold text-amber-900 underline-offset-2 hover:underline">
            <ArrowLeft className="mr-1 inline h-3 w-3" /> Back to listing
          </Link>
        </div>
      </div>

      {/* Branded hero */}
      <section className="relative border-b" style={{ background: wash, borderColor: `${accent}22` }}>
        <div className="container py-12 md:py-20">
          <div className="flex flex-col items-start gap-6 md:flex-row md:items-center">
            <div
              className="flex h-16 w-16 items-center justify-center rounded-2xl text-xl font-bold text-white shadow-product"
              style={{ background: accent }}
            >
              {initials}
            </div>
            <div className="min-w-0">
              <p className="text-xs font-semibold uppercase tracking-[0.16em]" style={{ color: accent }}>
                Refer a customer to
              </p>
              <h1 className="mt-1 text-3xl font-extrabold tracking-tight text-foreground md:text-5xl">
                {listing.name}
              </h1>
              <p className="mt-1 text-sm text-muted-foreground">{listing.city}, {listing.region} · {listing.category}</p>
            </div>
          </div>

          {/* Big offer card */}
          <div className="mt-10 grid items-center gap-8 rounded-3xl border bg-card p-6 shadow-product md:grid-cols-2 md:p-10" style={{ borderColor: `${accent}33` }}>
            <div>
              <div className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-white" style={{ background: accent }}>
                <Sparkles className="h-3 w-3" /> Referral offer
              </div>
              <p className="mt-4 text-5xl font-extrabold tracking-tight text-foreground md:text-6xl">
                Earn <span style={{ color: accent }}>${listing.referral_fee.toLocaleString()}</span>
              </p>
              <p className="mt-2 text-base text-foreground/80">{listing.referral_fee_unit}</p>
              <p className="mt-4 text-sm text-muted-foreground">
                Refer someone who needs {listing.category.toLowerCase()} work. When their project closes with {listing.name}, you get paid directly by the business — Revvin doesn't take a cut.
              </p>
              <div className="mt-6">
                <ContactBusinessDialog
                  slug={listing.slug}
                  businessName={listing.name}
                  kind="referral"
                  title={`Submit a referral to ${listing.name}`}
                  description="The business will reach out to your contact within 1 business day."
                  trigger={
                    <Button size="lg" className="h-12 px-7 text-base hover:bg-primary-deep" style={{ background: accent, borderColor: accent }}>
                      <UserPlus className="mr-2 h-4 w-4" /> Submit a referral
                    </Button>
                  }
                />
              </div>
            </div>

            {/* QR */}
            <div className="flex justify-center">
              <div className="rounded-2xl border bg-card p-5 shadow-soft" style={{ borderColor: `${accent}33` }}>
                <p className="text-center text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                  Share this page
                </p>
                <div className="mt-3">
                  <SimpleQRCode url={url} size={180} />
                </div>
                <p className="mt-3 max-w-[200px] text-center text-[10px] text-muted-foreground">
                  Scan, text, or email — every referral routes back here.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How it works for the referrer */}
      <section className="border-b border-border">
        <div className="container py-16 md:py-20">
          <h2 className="text-2xl font-bold tracking-tight text-foreground md:text-3xl">How it works</h2>
          <div className="mt-8 grid gap-6 md:grid-cols-3">
            {[
              { n: "1", t: "Submit your referral", d: `Share your friend's name and best way to reach them.` },
              { n: "2", t: "We close the project", d: `${listing.name} contacts your referral, quotes the work, and gets the job done.` },
              { n: "3", t: "You get paid", d: `${listing.name} pays you $${listing.referral_fee.toLocaleString()} directly when the deal closes.` },
            ].map((s) => (
              <div key={s.n} className="rounded-xl border border-border bg-card p-5">
                <div className="flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold text-white" style={{ background: accent }}>
                  {s.n}
                </div>
                <h3 className="mt-3 text-base font-bold text-foreground">{s.t}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{s.d}</p>
              </div>
            ))}
          </div>
          <p className="mt-8 text-xs text-muted-foreground">
            <CheckCircle2 className="mr-1 inline h-3 w-3 text-primary" />
            100% of the referral fee goes to you. Revvin provides the page and lead tracking; payment is handled directly between you and {listing.name}.
          </p>
        </div>
      </section>

      {/* Powered by + share */}
      <section className="container py-10">
        <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground">
          <p>Powered by <span className="font-semibold text-foreground">Revvin</span> — referral pages for local businesses.</p>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" asChild>
              <Link to={`/business/${listing.slug}`}>View business profile</Link>
            </Button>
            <Button variant="outline" size="sm" onClick={() => { if (navigator.share) navigator.share({ url, title: listing.name }); }}>
              <Share2 className="mr-1.5 h-3 w-3" /> Share
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}