// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-offers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_offers_default = defineTool({
  name: "search_offers",
  title: "Search referral offers",
  description: "Search Revvin's public marketplace of referral offers. Filter by keyword, industry/category, city, or minimum payout. Returns active, approved offers from listed businesses.",
  inputSchema: {
    query: z.string().optional().describe("Keyword to match in offer title/description or business name."),
    category: z.string().optional().describe("Industry/category filter (e.g. 'Home Services', 'Legal')."),
    city: z.string().optional().describe("City name to filter businesses by."),
    min_payout: z.number().optional().describe("Minimum referral payout amount in the offer's currency."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, city, min_payout, limit }) => {
    const supabase = sb();
    let q = supabase.from("offers").select(
      "id, title, description, category, payout, payout_type, currency, location, businesses!inner(id, name, city, state, slug, marketplace_listed, account_status)"
    ).eq("status", "active").eq("approval_status", "approved").eq("businesses.marketplace_listed", true).limit(limit ?? 20);
    if (category) q = q.ilike("category", `%${category}%`);
    if (min_payout != null) q = q.gte("payout", min_payout);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (city) q = q.ilike("businesses.city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const rows = (data ?? []).map((o) => ({
      id: o.id,
      title: o.title,
      category: o.category,
      payout: o.payout,
      payout_type: o.payout_type,
      currency: o.currency,
      location: o.location,
      business: o.businesses?.name,
      city: o.businesses?.city,
      state: o.businesses?.state,
      url: o.businesses?.slug ? `https://revvin.co/offer/${o.businesses.slug}/${o.id}` : `https://revvin.co/offer/${o.id}`
    }));
    return {
      content: [{ type: "text", text: `Found ${rows.length} offer(s):
${JSON.stringify(rows, null, 2)}` }],
      structuredContent: { offers: rows }
    };
  }
});

// src/lib/mcp/tools/get-offer.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_offer_default = defineTool2({
  name: "get_offer",
  title: "Get offer details",
  description: "Fetch full details for a single Revvin referral offer by its ID, including business info and payout terms.",
  inputSchema: {
    offer_id: z2.string().uuid().describe("The offer's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id }) => {
    const supabase = sb2();
    const { data, error } = await supabase.from("offers").select(
      "id, title, description, category, payout, payout_type, currency, location, remote_eligible, qualification_criteria, close_time_days, deal_size_min, deal_size_max, status, approval_status, businesses(id, name, slug, city, state, website, description, phone, verified)"
    ).eq("id", offer_id).limit(1);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data || data.length === 0) return { content: [{ type: "text", text: "Offer not found." }], isError: true };
    const offer = data[0];
    return {
      content: [{ type: "text", text: JSON.stringify(offer, null, 2) }],
      structuredContent: { offer }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List offer categories",
  description: "List the distinct industry categories currently represented in the Revvin marketplace.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = sb3();
    const { data, error } = await supabase.from("offers").select("category").eq("status", "active").eq("approval_status", "approved").limit(1e3);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const cats = Array.from(new Set((data ?? []).map((r) => r.category).filter(Boolean))).sort();
    return {
      content: [{ type: "text", text: JSON.stringify(cats, null, 2) }],
      structuredContent: { categories: cats }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "revvin-mcp",
  title: "Revvin Marketplace",
  version: "0.1.0",
  instructions: "Tools for browsing Revvin's public marketplace of referral offers. Use `search_offers` to find offers by keyword, category, city, or minimum payout; `get_offer` to fetch full details for a specific offer; and `list_categories` to discover available industry categories. All tools return public marketplace data \u2014 no authentication required.",
  tools: [search_offers_default, get_offer_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
